### ISSUE TITLE
ID Eingabe

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/Mathezentrum#13]
Wo soll die Info stehen, wie sich die ID zusammensetzt?

**Comment by sheepyhollow** [comment]
Außerdem stimmt die Prüfung noch nicht, die ID hat 8 Stellen (nicht 9)

**Comment by sheepyhollow** [comment]
> Wo soll die Info stehen, wie sich die ID zusammensetzt?

Das gab es mal als "Tooltip" (oder wie das heißt) unter der Eingabezeile. Fand ich aber nicht ganz so glücklich, weil es doch viel Text ist. Ideen? Infobox zum Aufklappen oder so?

**Comment by MesoBolt** [comment]
Also bei mir hat die ID 9 Stellen und die Prüfung funktioniert.

**Comment by sheepyhollow** [comment]
ID soll aber 8 Stellen haben. Die "Anleitung" sollte noch angezeigt werden, z.B. als _tooltip_ oder mit einem Info-Link (Popover mit Anleitung). 
Zur Dokumentation: 
- die ersten 2 Buchstaben des Vornamens Ihrer Mutter. 
- die 2 Ziffern des Geburts*tag*s Ihrer Mutter. 
- 2 Ziffern des eigenen Geburts*monats*. 
- 2 Ziffern der Nummer des eigenen Fachbereichs.

**Comment by sheepyhollow** [comment]
Die Feldbezeichnung sollte `persönliche ID` sein (nicht Studenten-ID), um Verwechslungen mit Matrikelnummer und S-Nummer sowie das Gendern zu vermeiden.
