### ISSUE TITLE
Studiengang-Auswahlfeld

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/Mathezentrum#14]
Das Feld ist scrollbar, aber unten abgeschnitten. Laut Ralf ist es nicht offensichtlich scrollbar - da warte ich noch auf einen Screenshot.

**Comment by sheepyhollow** [comment]
Außerdem sollten die Studiengänge in alphabetischer Reihenfolge angezeigt werden.

**Comment by sheepyhollow** [comment]
![image](https://user-images.githubusercontent.com/13869236/64698456-36766f80-d4a3-11e9-8caf-80c88774ddcb.png)

**Comment by mimischi** [comment]
Habe gestern das Design aufgeräumt. Es verschwindet jetzt nicht mehr im Container.

Sortiert wird aber noch nichts.

**Comment by MesoBolt** [comment]
Habe Sortierung hinzugefügt.

**Comment by sheepyhollow** [comment]
Yay! Dann kann man dieses issue schließen.
