### ISSUE TITLE
Zeitangaben

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/Mathezentrum#15]
Der Time-Picker hat noch optische Issues und wohl auch Schwierigkeiten bei der Dateneingabe.
Evtl. lässt man die Limitierung der Zeiten ganz weg? Diskutiere ich nochmal mit Ralf.

**Comment by mimischi** [comment]
Man kann es so lösen wie bei Clock aktuell. Hier gibt es keine Limitierung durch die Picker. Nur die Validierung checkt, dass die Endzeit nicht vor der Startzeit liegt und vice versa.

**Comment by sheepyhollow** [comment]
Zeitvalidierung gelöst, so dass immer auf 8:00 zurückgesetzt wird.
Optisches Problem (Schatten hinter TimePicker) händisch gelöst (`max-width="290"` in `v-menu`)
Vllt. hat hier @mimischi noch eine pfiffige Idee?
