### ISSUE TITLE
ID-Step required

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/Mathezentrum#19]
Ich kann beim ersten Stepper Form (Studenten-ID, sollten wir noch gendern) einfach `Weiter` klicken und komme auf Step 2.

Sobald ich aber eines der Eingabefelder angetippt habe, wird der Button ausgegraut und ich muss etwas eingeben. 

Ich kläre nochmal, ob Input ohne ID-Angaben erlaubt sein sollen oder nicht (ich meine schon; man kann ja auch eine Fake-ID angeben).
Dann muss die Regel aber schon zu Beginn angewandt werden.

**Comment by mimischi** [comment]
Das habe ich gestern gelöst. Allerdings ist eben der Button ausgegraut.

**Comment by sheepyhollow** [comment]
Nochmal prüfen, dann schließen.
