### ISSUE TITLE
Kommentarfeld

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/Mathezentrum#20]
im letzten Step soll unter den Zeiten ein Kommentarfeld hinzugefügt werden, d.h. man muss den `attendees`-Datensatz noch um ein Kommentarfeld erweitern.

**Comment by MesoBolt** [comment]
Kommentarfeld habe ich hinzugefügt. In der Download-CSV Datei ist der Platzhalter bei leerem Textfeld "undefined".

**Comment by sheepyhollow** [comment]
sollte das nicht eher `""` (empty string) sein?
