### ISSUE TITLE
Link zum Admin-Menü

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/Mathezentrum#4]
das Admin-Menü soll über einen Link auf der Eingabeseite verfügbar sein.
Danach muss es eine Passwortabfrage geben (wie macht man das am besten @mimischi )?

**Comment by mimischi** [comment]
Den Link per `<router-link to="/admin">Admin</router-link>`, siehe https://router.vuejs.org/guide/#html. Die Passwort Abfrage ggf. per [Navigation Guards](https://router.vuejs.org/guide/advanced/navigation-guards.html) -- müsste ich aber auch noch mal darüber nachdenken.

**Comment by MesoBolt** [comment]
Der Link ist nun versteckt - ohne Passwort.

**Comment by sheepyhollow** [comment]
Kann man das Passwort nicht ähnlich wie Environment-Variablen lösen?

**Comment by mimischi** [comment]
Mein ursprünglicher Vorschlag war viel zu komplex. Man kann das Ganze auch wirklich simpel lösen: https://codesandbox.io/embed/mathezentrumapp-4h8zs

Per `v-if` wird ein Login-Formular gezeigt, wenn der User nicht authentifiziert ist. Im anderen Fall wird die Teilnehmerliste gezeigt. Die Authentifizierung wird vergessen, sobald man die Seite neu lädt bzw. zurück auf "Home" klickt.

Habe für das Beispiel die Bilder entfernt, da das irgendwie nicht mit Codesandbox ging.

**Comment by MesoBolt** [comment]
Aber theoretisch ist das Passwort für jeden auffindbar, wenn man sich im Browser den Code ansieht oder ?

**Comment by mimischi** [comment]
Ja und das ist bei JavaScript mit allen Dingen so! Das kann man nur lösen, wenn die Authentifizierung mit einer Anfrage an einen externen Service verbunden ist. Das können wir hier aber nicht machen, da wir davon ausgehen die Endgeräte sind immer offline.

Man könnte beim ersten Start der App auch den Admin ein Master-Passwort festlegen lassen. Das könnten wir dann im localstorage speichern.

Da aber die Nutzung der App nur am Tablet stattfinden wird, wird sich niemand den Source Code anschauen.

**Comment by MesoBolt** [comment]
Okay, ich denke auch nicht, dass wir bei den Mathematikern oder Physikern solche "Hacker" haben werden...

**Comment by sheepyhollow** [comment]
Nach dem letzten Hack von @mimischi ist das PW in einer .env- Variable mit HelloWorld-Fallback zum Testen. Die Umgebungsvariable müsste noch in Netlify eingebastelt werden.

**Comment by sheepyhollow** [comment]
Wir sollten aber auch noch einen `logout`-Button haben

**Comment by sheepyhollow** [comment]
gelöst mit #23
