### ISSUE TITLE
Form des Datenexports

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/Mathezentrum#5]
Der Datenexport soll folgende Felder beinhalten
`Datum; ID; Startuhrzeit; Enduhrzeit; Dauer; Fachsemester; Studiengang; Kurse...`

- `Datum` als separate Information (DD.MM.YYYY)
- `Dauer` kann man auch beim Auswerten berechnen, aber wenn wir es mitliefern, spart es einen Schritt; die Zeiten sollen aber trotzdem dabei sein
- `Uhrzeiten` als (HH:MM)

Für die Kurse brauchen wir aber noch eine gute Lösung:
a.  n Spalten für n Kurse; in jeder belegten Spalte steht eine "1"
b. gleiches Prinzip wie (a) aber als Binärzahl in einer Spalte "10010000010"
c. angekreuzte Spalten nacheinander, ist aber schwerer auszuwerten, da für jeden User unterschiedlich

**Comment by mimischi** [comment]
Was ist denn mit einer Art des aktuellen? Alle ausgewählten Kurse stehen in einer Spalte, sind aber durch Kommas getrennt.

```
Datum; ID; Startuhrzeit; Enduhrzeit; Dauer; Fachsemester; Studiengang; Kurse
16.05.2019; 123456; 10:00; 12:00; 02:00; 5; Biochemie;Mathe,Physik,Chemie
```

**Comment by sheepyhollow** [comment]
Man muss es in Excel dann halt gut auseinanderfieseln können.
Die Idee, dass jede LV ihre Spalte hat, bietet den Vorteil, dass man auf einen Blick sieht, für welche Veranstaltungen am häufigsten gearbeitet wird. Das kann man mit einer Komma-Liste einfach nicht so gut. Die Reihenfolge stimmt zwar, aber es gibt Lücken.

**Comment by MesoBolt** [comment]
Das heißt dann aber auch, dass es eine sehr breite Tabelle wird, wenn alle möglichen Kurse abgedeckt werden sollen.

**Comment by sheepyhollow** [comment]
Das ist ja das charmante an b) :wink:

**Comment by mimischi** [comment]
Bin mit meinem Binärwissen gar nicht fit. Kann man das denn tatsächlich einfach auseinanderfriemeln? Wie denn?

**Comment by sheepyhollow** [comment]
Naja, ist bisschen Spielerei. Der Witz ist, dass man nur eine Zahl speichern muss, z.B. `181`.
Binär ist das dann `10110101`, d.h. "Item 1, Item 3, Item 4, Item 6, Item 8". 
Man braucht dazu aber noch den "Schlüssel" (= die Reihenfolge der Kurse).

Aber man überträgt eben nur eine Zahl pro Eintrag. Wie man das dann auseinanderzieht, muss der Mathematiker wissen 😄

**Comment by sheepyhollow** [comment]
json2csv tut nach wie vor nicht, was es soll - es übernimmt keine Spaltennamen (`fields`) und man müsste das Objekt umsortieren, damit die richtige Datenreihenfolge im File landet (JS einmaleins aber ich weiß nicht, wie)
Ich habe jetzt nach viel Rumärgern den Export mit dem Holzhammer manuell geschrieben. Bestimmt nicht elegant, aber die Daten sehen so aus, wie sie sollen. Aber Verbesserungsvorschläge nehme ich gerne. 
Weiter ungeklärt ist aber die offene Frage zu den `courses` und das UTF-8 Problem. Windows erwartet nämlich ISO-8859-1 🙄

**Comment by sheepyhollow** [comment]
Der Export an sich wäre gelöst. Der nächste Schritt wäre jetzt eine gute Lösung für die `courses`. 
Das müsste aber schon in `AttendeeForm` passieren - bzw. wenn wir die Kursliste im Adminbereich erstellen können, dann vllt. auch dort.

**Comment by mimischi** [comment]
Das hängt jetzt eben von der Lösung ab. Wenn es bitwise sein soll, dann müssen wir den Kursen noch eine ID geben!

**Comment by sheepyhollow** [comment]
Ralf schreibt dazu:
> diese werden derzeit alle in einem Feld gespeichert und zwar als Text in der Reihenfolge, wie sie angeklickt wurden. Das macht eine Auswertung danach, für welches Fach jemand da  war, sehr schwierig (man müsste wohl jeden String nach jedem Veranstaltungsnamen absuchen oder so).

> Könnte man nicht für jede Veranstaltung, die man auswählen kann, ein eigenes Feld (= in Excel eine eigene Spalte) haben (mit dem Veranstaltungsnamen als Titel / Spaltenüberschrift), die default auf 0 gesetzt ist und wenn die Veranstaltung ausgewählt ist, auf 1 gesetzt wird (entsprechend wieder auf 0, wenn sie wieder abgewählt wird)?

> (von mir aus auch als Array mit 0/1-Einträgen, dann muss halt nur die Zuordnung Veranstaltung -> Position im Array konsistent und klar sein)

**Comment by sheepyhollow** [comment]
Ich schau mir das nochmal an. Wäre es denn sinnvoll, die Courselist in den local storage zu schreiben? Irgendwie schon, oder?

**Comment by mimischi** [comment]
> 

    Könnte man nicht für jede Veranstaltung, die man auswählen kann, ein eigenes Feld (= in Excel eine eigene Spalte) haben (mit dem Veranstaltungsnamen als Titel / Spaltenüberschrift), die default auf 0 gesetzt ist und wenn die Veranstaltung ausgewählt ist, auf 1 gesetzt wird (entsprechend wieder auf 0, wenn sie wieder abgewählt wird)?
Ja das können wir machen, wenn er die Ausgabe so wünscht!

> Wäre es denn sinnvoll, die Courselist in den local storage zu schreiben? Irgendwie schon, oder?

Die `courselist` ist die Liste an Auswählbaren Kursen, korrekt? Die kann sich natürlich je nach Semester ändern. Im localstorage müssten wir das also nicht anpassen.

Denkbar wäre folgende Lösung:
Im Adminbereich gibt es einen Knopf "Default Kurse Wiederherstellen". Das schreibt eine festgelegte Liste (wie jetzt, fest im Code drin) in den local storage. Diese lässt sich aber nach belieben dann per Hand bearbeiten, also Kurse löschen bzw. hinzufügen. Ändert sich nun etwas, i.e., ein Kurs verschwindet für immer aus dem Curriculum, könnten wir den auch dann im Code entfernen.

**Comment by sheepyhollow** [comment]
Ist als Matrix (fast) gelöst. Auch der letzte Punkt ist angedacht.
